


Firts, create a directory and store all the paired-end sequences for each individual in this folder. Also stored the reference genome there 

#### Aligning Sequences

Is important to note that for hundreds of PE sequences the name of the files is usually like teo1_1.fq and teo1_2.fq. However, this scritp considers eliminate the column of the PE direction 
    
     for i in *.fq; do yolo=$(echo "$i" | rev | cut -c 6- | rev | uniq); bwa mem index_tic_geno ${yolo}_1.fq ${yolo}_2.fq -t 20 | samtools view -Sb -@ 20 - > ${yolo}.bam; done &> radseq_10_14.txt &
     
 #### The output from above are bam files usorted, then sort the bamfiles

    for f in *.bam; do samtools sort -@ 30 $f > ${f%\.*}_sorted.bam; done &
 
The bamfiles are now sorted and then its time to call the genotypes. This can be achieved using samtools and some script provided by the pipeline of Lep-MAP3, please consult: https://sourceforge.net/u/lep-map/profile/ to download the program and the script

#### Calling genotype posterior probabilities

This is for variant calling and convert to posterior probabilities using Lep-MAP3, this pipeline requieres two files, one with the names of the bam files with the extension and other without the extensions ".bam" is very important that invididual files (alignment) most be in the same order. For example:

sorted_bams: 1.bam 2.bam 3.bam....with extension

mapping.txt: 1 2 3....without the extension

Then use this command to call genotypes 

    samtools mpileup -q 10 -Q 10 -s $(cat sorted_bams)|awk -f pileupParser2.awk|awk -f pileup2posterior.awk|gzip >post.gz

#### It is time to use Lep-MAP3

First, generate a pedigree file. This file most be in this format

CHR POS F   F   F   F   F   F
CHR POS female  male    progeny_1   progeny_2   progeny_3   progeny_4
CHR POS 0   0   male    male    male    male
CHR POS 0   0   female  female  female  female
CHR POS 2   1   0   0   0   0
CHR POS 0   0   0   0   0   0

Then use this command to transpose the file for the firts module of Lep-MAP3

    ./transpose_tab pedigree.txt|awk '{print "CHR\tPOS\t"$0}' >ped_t.txt

#### Firts module from Lep-Map3, ParentCall2
    
   Parentcall
	
    java -cp bin/ ParentCall2 data=ped_t.tx posteriorFile=post removeNonInformative=1 >data.post.call

#### Filtering the posterior probabilities of the genotypes

    java -cp bin/ Filtering2 data=data.post.call dataTolerance=0.0001 removeNonInformative=1 >data_f.post.call
    
#### SeparateChromosome2
   
   This module is to separate the markers into chromosomes, there is not a best predefined lodLimit=20. The best one should be obtaing running with different values. Please test as much you can to observe the distribution of the markers, compare and select the best distribution of the markers in the LGs generated by this module. For instance, try between 20-70 lodLimit

    java -cp bin/ SeparateChromosomes2 lod3Mode=3 data=data_f.post.call lodLimit=20 sizeLimit=10 >map20.txt &
    
 With this script you can check the sixe distribution of the markers in th linkage groups (LGs)
 
    sort bestLOD15_refinedfrom_map15.txt|uniq -c|sort -n
    
 You also can refined the map using the previous run and improve the mapping, map15.txt is the map created by SeparateChromosomes in a previous run
 
    java -cp bin/ SeparateChromosomes2 map=map15.txt lod3Mode=2 data=data_f.post.call lodLimit=12 sizeLimit=53 >bestLOD15_refinedfrom_map15.filtered.txt
    
  #### JoinSingles2All
  
  This module helps to asssing single markers to the existing LGs, join singles can be iterated. I recommend five times

	java -cp bin/ JoinSingles2All lod3Mode=3 map=JoinSingles2All.map15.txt data=data_f.post.call lodLimit=10 > JoinSingles2All.mapChrDatura.sizelimitfor12LGs.5.txt
  
 With this script you can see the size distribution of linkage groups from JoinSingles2All
 
	cut -f 1 map15.joinsingle.refinedLOD15.txt|sort|uniq -c|sort -n
    
 #### Ordering markers
 
 Now its time to order all marker of the LGs, you have to do this for all chromosomes, this can be set using "chromosome=1"
 
Iterate for all chromosomes

	java -cp bin/ OrderMarkers2 map=JoinSingles2All.mapChrDatura.sizelimitfor12LGs.5.txt data=data_f.post.call outputPhasedData=1 grandparentPhase=1 sexAveraged=1 chromosome=1 >order1.codvid19.txt 2>order1.err

Evaluate Order, iterate for all chromosomes, iterate two times

	java -cp bin/ OrderMarkers2 evaluateOrder=order1.codvid19.txt data=data_f.post.call outputPhasedData=1 grandparentPhase=1 sexAveraged=1 chromosome=1 >order1.evaluated.txt 2>order1.evaluated.err
    
 #### chromosomes were concatenated and then I can run map2genotypes from Lep-MAP3, it works just like that, then you obtain a file without the number of chromosome information

cat order1.evaluated.txt order2.evaluat3.evaluated.txt......>allchr.txt

This script converts to phase genotypes. This measn that one allele comes from one parent and the other from the other parent. 1 2 are the alles. This files does not give you the number of the chromosome but this is very easy to set. 

awk -vfullData=1 -f map2genotypes.awk All.Chr.Concatenated.Covid9.txt >genotypes.txt

To put the number of the chromosome you can do this manually in excel using the concatenated and the order files. Then you can see the name of the markers, where markers starts and ends. Then just assing the number of LG

	THIS GENOTYPES ARE NOW ALMOST READY TO USE FOR QTL ANALYS   

